spring:
  application:
    name: test
  cloud:
    zookeeper:
      connect-string: 47.99.68.19:2181
      enabled: true
#      properties:
#        authProvider:1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
#        requireClientAuthScheme: sasl
#        jaasLoginRenew: 3600000
